package com.streampanel.core.database

import com.streampanel.core.model.ActionType
import com.streampanel.core.model.ButtonState

object SeedData {
    const val PROFILE_ID = "default-profile"
    const val HOME_PAGE_ID = "home-page"
    const val AUTOMATION_PAGE_ID = "automation-page"
    const val APPS_PAGE_ID = "apps-page"

    val profile = ProfileEntity(
        id = PROFILE_ID,
        name = "Studio Command Center",
        isActive = true,
    )

    val pages = listOf(
        PageEntity(HOME_PAGE_ID, PROFILE_ID, null, "Main Deck", 0),
        PageEntity(AUTOMATION_PAGE_ID, PROFILE_ID, HOME_PAGE_ID, "Automation", 1),
        PageEntity(APPS_PAGE_ID, PROFILE_ID, HOME_PAGE_ID, "Apps", 2),
    )

    val buttons = listOf(
        ButtonEntity(
            id = "btn-browser",
            pageId = HOME_PAGE_ID,
            title = "Open Studio",
            subtitle = "URL",
            iconName = "public",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#312E81",
            gradientEndColor = "#8B5CF6",
            row = 0,
            column = 0,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-hotkey",
            pageId = HOME_PAGE_ID,
            title = "Mute Mic",
            subtitle = "Ctrl+Shift+M",
            iconName = "mic_off",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#7F1D1D",
            gradientEndColor = "#EF4444",
            row = 0,
            column = 1,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Warning,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-text",
            pageId = HOME_PAGE_ID,
            title = "BRB Chat",
            subtitle = "Send text",
            iconName = "chat",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#064E3B",
            gradientEndColor = "#10B981",
            row = 0,
            column = 2,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-apps-folder",
            pageId = HOME_PAGE_ID,
            title = "Apps",
            subtitle = "Programs",
            iconName = "terminal",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#1E1B4B",
            gradientEndColor = "#6366F1",
            row = 1,
            column = 0,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Active,
            targetPageId = APPS_PAGE_ID,
            isFolder = true,
        ),
        ButtonEntity(
            id = "btn-automation-folder",
            pageId = HOME_PAGE_ID,
            title = "Automation",
            subtitle = "Folder",
            iconName = "folder",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#1E293B",
            gradientEndColor = "#38BDF8",
            row = 1,
            column = 1,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Active,
            targetPageId = AUTOMATION_PAGE_ID,
            isFolder = true,
        ),
        ButtonEntity(
            id = "btn-chrome",
            pageId = APPS_PAGE_ID,
            title = "Chrome",
            subtitle = "Browser",
            iconName = "public",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#1D4ED8",
            gradientEndColor = "#60A5FA",
            row = 0,
            column = 0,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-discord",
            pageId = APPS_PAGE_ID,
            title = "Discord",
            subtitle = "Chat",
            iconName = "chat",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#4338CA",
            gradientEndColor = "#818CF8",
            row = 0,
            column = 1,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-spotify",
            pageId = APPS_PAGE_ID,
            title = "Spotify",
            subtitle = "Music",
            iconName = "music_note",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#166534",
            gradientEndColor = "#4ADE80",
            row = 0,
            column = 2,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-notepad",
            pageId = AUTOMATION_PAGE_ID,
            title = "Notepad",
            subtitle = "Launch",
            iconName = "terminal",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#111827",
            gradientEndColor = "#6B7280",
            row = 0,
            column = 0,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
        ButtonEntity(
            id = "btn-delay-sequence",
            pageId = AUTOMATION_PAGE_ID,
            title = "Macro",
            subtitle = "Text after delay",
            iconName = "bolt",
            imageUri = null,
            gifUri = null,
            backgroundColor = "#581C87",
            gradientEndColor = "#D946EF",
            row = 0,
            column = 1,
            rowSpan = 1,
            columnSpan = 1,
            state = ButtonState.Idle,
            targetPageId = null,
            isFolder = false,
        ),
    )

    val actions = listOf(
        ActionEntity(
            id = "act-browser",
            buttonId = "btn-browser",
            type = ActionType.OpenUrl,
            label = "Open website",
            payload = mapOf("url" to "https://www.youtube.com"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-hotkey",
            buttonId = "btn-hotkey",
            type = ActionType.Hotkey,
            label = "Mute microphone",
            payload = mapOf("keys" to "CTRL+SHIFT+M"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-text",
            buttonId = "btn-text",
            type = ActionType.SendText,
            label = "Send chat text",
            payload = mapOf("text" to "I'll be right back!"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-notepad",
            buttonId = "btn-notepad",
            type = ActionType.LaunchProcess,
            label = "Launch Notepad",
            payload = mapOf("path" to "notepad.exe"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-chrome",
            buttonId = "btn-chrome",
            type = ActionType.LaunchProcess,
            label = "Launch Chrome",
            payload = mapOf("path" to "chrome.exe"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-discord",
            buttonId = "btn-discord",
            type = ActionType.LaunchProcess,
            label = "Launch Discord",
            payload = mapOf("path" to "%LOCALAPPDATA%\\Discord\\Update.exe --processStart Discord.exe"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-spotify",
            buttonId = "btn-spotify",
            type = ActionType.LaunchProcess,
            label = "Launch Spotify",
            payload = mapOf("path" to "spotify.exe"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-delay",
            buttonId = "btn-delay-sequence",
            type = ActionType.Delay,
            label = "Wait",
            payload = mapOf("durationMs" to "750"),
            sortOrder = 0,
        ),
        ActionEntity(
            id = "act-sequence-text",
            buttonId = "btn-delay-sequence",
            type = ActionType.SendText,
            label = "Type after delay",
            payload = mapOf("text" to "Macro executed from StreamPanel."),
            sortOrder = 1,
        ),
    )
}
