package com.streampanel.core.designsystem

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.streampanel.core.model.AppLanguage
import com.streampanel.core.model.DashboardPanelId
import com.streampanel.core.model.DashboardZone
import com.streampanel.core.model.ThemeMode
import com.streampanel.core.model.ToolsColumnWidth

open class AppStrings {
    open val appName = "StreamPanel"
    open val controlDeck = "Control Deck"
    open val connect = "Connect"
    open val disconnect = "Disconnect"
    open val connecting = "Connecting..."
    open val offline = "Offline"
    open val online = "Online · PC linked"
    open val connectionError = "Connection error"
    open val newLayer = "New layer"
    open val delete = "Delete"
    open val newMacro = "New macro"
    open val grid = "Grid"
    open val ready = "Ready"
    open val edit = "Edit"
    open val back = "Back"
    open val save = "Save"
    open val saved = "Saved"
    open val name = "Name"
    open val tabDeck = "Deck"
    open val tabTools = "Tools"
    open val tabMenu = "Menu"
    open val deckTitle = "Deck"
    open val quickActions = "Quick Actions"
    open val quickActionsSub = "One-tap PC shortcuts"
    open val systemAudio = "System Audio"
    open val systemAudioSub = "Control PC volume in real time"
    open val media = "Media"
    open val playing = "Playing"
    open val paused = "Paused"
    open val micMute = "Mic mute"
    open val micOff = "Mic off"
    open val speakers = "Speakers"
    open val headphones = "Headphones"
    open val quickLaunch = "Quick Launch"
    open val quickLaunchSub = "Open programs on your PC"
    open val navigation = "Navigation"
    open val navigationSub = "Folders and URL groups"
    open val windowsSystem = "Windows & System"
    open val windowsSystemSub = "Hold Sleep to confirm"
    open val moveToMonitor = "Move to monitor"
    open val moveToMonitorSub = "Moves the active window to the selected display"
    open fun monitor(n: Int) = "Monitor $n"
    open val minimizeAll = "Minimize all"
    open val maximize = "Maximize"
    open val snapLeft = "Snap left"
    open val snapRight = "Snap right"
    open val minimizeWin = "Minimize win"
    open val screenshot = "Screenshot"
    open val taskManager = "Task Manager"
    open val killProcess = "Kill process"
    open val sleep = "Sleep"
    open val obsStudio = "OBS Studio"
    open val pcServer = "PC Server"
    open val appearance = "Appearance"
    open val settings = "Settings"
    open val settingsOverviewSub = "Quick snapshot before you dive into sections"
    open val settingsOverviewHint = "Open only the section you need. Most changes are saved automatically."
    open fun layerGridTitle(name: String) = "Layer grid - $name"
    open val layerGridHint = "Grid size for this layer (2-8)."
    open val columns = "Columns"
    open val rows = "Rows"
    open val apply = "Apply"
    open val cancel = "Cancel"
    open fun macroActionsTitle(title: String) = title
    open val macroActionsBody = "Edit macro steps or delete this button."
    open val sleepConfirmTitle = "Put PC to sleep?"
    open val sleepConfirmBody = "The computer will enter sleep mode."
    open val sleepNow = "Sleep now"
    open fun controlsCount(cols: Int, rows: Int, count: Int) = "$cols x $rows · $count controls"
    open val language = "Language"
    open val languageSub = "Interface language"
    open val english = "English"
    open val russian = "Russian"
    open val focusTracking = "Auto layer switch"
    open val focusTrackingSub = "Switches deck layer when active PC app changes"
    open val focusTrackingToggle = "Switch layer by active app"
    open val focusTrackingHint = "Add rules via deck export: processPattern -> pageId."
    open val hwMonitor = "Hardware"
    open val hwMonitorSub = "Live CPU, RAM & network from your PC"
    open val clipboard = "Clipboard"
    open val clipboardSub = "Share text between PC and phone"
    open val pasteFromPc = "Paste from PC"
    open fun foregroundApp(app: String) = "Active: $app"
    open val cpu = "CPU"
    open val ram = "RAM"
    open val disk = "Disk"
    open val storage = "Storage"
    open val storageFree = "free"
    open fun networkDown(v: String) = "↓ $v Mbps"
    open fun networkUp(v: String) = "↑ $v Mbps"
    open val obsStream = "Stream"
    open val obsRecord = "Record"
    open val obsScenes = "Scenes"
    open val obsSources = "Sources"
    open val obsReplay = "Replay"
    open val obsVirtualCam = "Virtual cam"
    open val obsStudioMode = "Studio"
    open val obsRefresh = "Refresh"
    open val obsConnect = "Connect"
    open val obsUrl = "WebSocket URL"
    open val obsPassword = "Password"
    open val lock = "Lock"
    open val paste = "Paste"
    open val desktop = "Desktop"
    open val sync = "Sync"
    open val copy = "Copy"
    open val altTab = "Alt+Tab"
    open val closeWin = "Close"
    open val fullscreen = "F11"
    open val refresh = "Refresh"
    open val undo = "Undo"
    open val cut = "Cut"
    open val redo = "Redo"
    open val search = "Search"
    open val newTab = "New tab"
    open val previousTrack = "Prev track"
    open val nextTrack = "Next track"
    open val discordTitle = "Discord"
    open val discordSub = "Opens Discord and sends useful hotkeys"
    open val discordOpen = "Open"
    open val discordMute = "Mute"
    open val discordDeafen = "Deafen"
    open val discordPtt = "PTT"
    open val pomodoroTitle = "Focus Timer"
    open val pomodoroFocus = "Focus mode"
    open val pomodoroIdle = "Focus session"
    open val pomodoroStart = "Start"
    open val pomodoroStop = "Stop"
    open val pomodoroMinutes = "Focus minutes"
    open val timeTrackerTitle = "Time tracker"
    open val timeTrackerIdle = "Tap project to start"
    open val timeTrackerStopLog = "Stop & log"
    open val processTitle = "Heavy processes"
    open val processSub = "Tap to kill"
    open val cleanTemp = "Clean Temp folders"
    open val devToolsTitle = "Dev & Git"
    open val devToolsSub = "Docker, Git, IDE shortcuts"
    open val gitPull = "Git pull"
    open val gitStatus = "Git status"
    open val dockerPs = "Docker ps"
    open val dockerUp = "Compose up"
    open val vscodeTest = "Run tests"
    open val vscodeFormat = "Format"
    open val vscodeTerminal = "Terminal"
    open val wifiRestart = "Restart Wi-Fi"
    open val flushDns = "Flush DNS"
    open val emptyRecycleBin = "Empty recycle bin"
    open val streamToolsTitle = "Stream Tools"
    open val streamToolsSub = "OBS, dashboards, chat and clips"
    open val streamToolsHint = "Twitch/YouTube open creator dashboards. Chat opens your Stream Kit URL group from settings."
    open val streamChatTitle = "Stream Chat"
    open val streamChatSub = "Twitch and YouTube chat on the deck"
    open val streamChatHint = "Set your Twitch channel or YouTube live video ID in settings."
    open val twitchChannel = "Twitch channel"
    open val youtubeVideoId = "YouTube live video ID"
    open val embedChatInDashboard = "Show chat inside dashboard"
    open val showTwitchChat = "Show Twitch chat"
    open val showYoutubeChat = "Show YouTube chat"
    open val twitchDashboard = "Twitch"
    open val youtubeStudio = "YouTube"
    open val openChat = "Chat"
    open val replayClip = "Replay/Clip"
    open val gameStatusTitle = "Game Status"
    open val gameStatusSub = "Auto game info from PC"
    open val gameStatusHint = "CS2 health/map/ammo need Game State Integration on the PC server."
    open val gameOverlaySettings = "Game overlay"
    open val gameOverlaySettingsSub = "Process detection, CS2 telemetry and useful game HUD"
    open val gameAutoProcesses = "Auto-show process names"
    open val showHealth = "Health"
    open val showAmmo = "Ammo"
    open val showMap = "Map"
    open val showScore = "Score"
    open val gameNotDetected = "No supported game detected"
    open val health = "Health"
    open val armor = "Armor"
    open val ammo = "Ammo"
    open val score = "Score"
    open val map = "Map"
    open val phase = "Phase"
    open val pcConfiguratorTitle = "PC Configurator"
    open val pcConfiguratorSub = "Open the web editor on your computer"
    open val pcConfiguratorHint = "Use the PC browser for faster editing with mouse and keyboard. The server already hosts the setup page."
    open val openPcConfigurator = "Open configurator"
    open val studyModeTitle = "Study Mode"
    open val studyModeSub = "Focus timer, notes and browser pack"
    open val studyModeHint = "Focus starts the timer. Study pack opens calendar, docs and AI helper."
    open val startFocus = "Focus"
    open val studyPack = "Study pack"
    open val notes = "Notes"
    open val meetingModeTitle = "Meeting Mode"
    open val meetingModeSub = "Mute and meeting apps"
    open val meetingModeHint = "Mic toggles system microphone mute. App buttons open Discord/Teams/Zoom on PC."
    open val teams = "Teams"
    open val zoom = "Zoom"
    open val pickFromGallery = "Pick from gallery"
    open val backgroundUrl = "Background image URL"
    open val themes = "Theme"
    open val themesSub = "Color palette for the app"
    open val glassPanels = "Glass panels"
    open val keepScreenOn = "Keep screen on"
    open val accentColor = "Accent color (#hex)"
    open val pcConnection = "PC Connection"
    open val pcConnectionSub = "WebSocket address of your Windows server"
    open val serverHost = "Server IP / host"
    open val port = "Port"
    open val pinCode = "PIN code"
    open val pinHint = "PIN protects the PC server. Leave empty if not set on Windows."
    open val autoConnect = "Auto-connect on launch"
    open val gridLayout = "Grid layout"
    open val gridLayoutSub = "Default button deck size"
    open val showOnPanel = "Show on panel"
    open val pathOrCommand = "Path or command"
    open val addProgram = "Add program"
    open val restoreDefaults = "Restore defaults"
    open val timeTrackerSettings = "Time tracker"
    open val timeTrackerSettingsSub = "Projects on dashboard · export CSV"
    open val timeTrackerStorageHint = "Entries are stored locally in app storage. Use Export CSV to get a copyable table."
    open val addProject = "Add project"
    open val exportCsv = "Export CSV"
    open fun entriesLogged(n: Int) = "$n entries logged"
    open val navigationFolders = "Navigation folders"
    open val navigationFoldersSub = "Explorer shortcuts"
    open val urlGroups = "URL groups"
    open val urlGroupsSub = "Open multiple links - separate with |"
    open val streamChatSettings = "Stream chat"
    open val streamChatSettingsSub = "Twitch/YouTube chat URLs for the dashboard"
    open val importExport = "Import / Export"
    open val importExportSub = "Backup or restore button deck as JSON"
    open val exportDeck = "Export deck"
    open val importDeck = "Import deck"
    open val pasteJsonImport = "Paste JSON to import"
    open val exportedJson = "Exported JSON"
    open val editorTitle = "Button Editor"
    open val livePreview = "Live Preview"
    open val visual = "Visual"
    open val subtitle = "Subtitle"
    open val icon = "Icon"
    open val imageUrl = "Image URL"
    open val gradient = "Gradient"
    open val activeIcon = "Active icon"
    open val activeColor = "Active color"
    open val iconPresets = "Icon presets"
    open val toggleMode = "Toggle mode"
    open val twoStateButton = "Two-state button (On/Off)"
    open fun macroSteps(n: Int) = "Macro steps ($n)"
    open fun step(n: Int) = "Step $n"
    open val actionType = "Action type"
    open val payloadKey = "Payload key"
    open val payloadValue = "Payload value"
    open val addStep = "Add step"
    open val macroTemplates = "Templates"
    open val simpleActions = "Simple actions"
    open val advancedPrograms = "Programmable macros"
    open val programMacroHint = "Programmable macros can run sequences, delays, variables, loops and conditions."
    open fun macroTemplateLabel(key: String) = when (key) {
        "browser" -> "Open browser"
        "website" -> "Open website"
        "app" -> "Open app"
        "obs_stream" -> "OBS Stream"
        "obs_replay" -> "Save Replay"
        "screenshot" -> "Screenshot"
        "discord_mute" -> "Discord Mute"
        "mic_mute" -> "Mic Mute"
        "focus_mode" -> "Focus Mode"
        "meeting_mute" -> "Meeting Mute"
        "study_pack" -> "Study Pack"
        "twitch_chat" -> "Twitch Chat"
        "youtube_studio" -> "YouTube Live"
        "pc_configurator" -> "PC Config"
        "cs2_gsi_help" -> "CS2 HUD"
        "window_layout" -> "Window Layout"
        "move_monitor_2" -> "Move to Monitor 2"
        "game_mode" -> "Game Mode"
        "stream_start_pack" -> "Stream Start"
        "work_focus_pack" -> "Work Focus"
        "program_sequence" -> "Sequence"
        "program_loop" -> "Loop"
        "program_timer" -> "Timer"
        "program_condition" -> "Condition"
        else -> key
    }
    open val colorPresets = "Color presets"
    open val rowSpan = "Row span"
    open val columnSpan = "Column span"
    open val navigatePageHint = "Pick target layer or paste ID:"
    open val launchAdminHint = "For UAC add another step: LaunchProcess, key runAsAdmin, value true"
    open val whenToggle = "When (toggle)"
    open val delayMs = "Delay ms"
    open val targetLayerId = "Target layer ID"
    open val folderPath = "Folder path"
    open val urls = "URLs"
    open val groupName = "Group name"
    open val project = "Project"
    open val layoutCustomization = "Layout"
    open val layoutCustomizationSub = "Reorder zones and panels, show or hide blocks"
    open val layoutZones = "Screen zones (tablet)"
    open val layoutZonesSub = "Order of sidebar, deck, and tools column"
    open val layoutPanels = "Panels"
    open val layoutPanelsSub = "Order and visibility of tool panels"
    open val layoutSidebarVisible = "Show sidebar on tablet"
    open val layoutToolsWidth = "Tools column width"
    open fun layoutZoneLabel(zone: DashboardZone) = when (zone) {
        DashboardZone.Sidebar -> "Sidebar (layers & connect)"
        DashboardZone.Deck -> "Deck (macro grid)"
        DashboardZone.ToolsColumn -> "Tools (panels)"
    }
    open fun layoutPanelLabel(id: DashboardPanelId) = when (id) {
        DashboardPanelId.HardwareMonitor -> "Hardware monitor"
        DashboardPanelId.ProcessMonitor -> "Process monitor"
        DashboardPanelId.DevTools -> "Dev / Git / Docker"
        DashboardPanelId.StreamTools -> "Stream tools"
        DashboardPanelId.StreamChat -> "Stream chat"
        DashboardPanelId.GameStatus -> "Game status"
        DashboardPanelId.PcConfigurator -> "PC configurator"
        DashboardPanelId.Discord -> "Discord"
        DashboardPanelId.StudyMode -> "Study mode"
        DashboardPanelId.MeetingMode -> "Meeting mode"
        DashboardPanelId.Pomodoro -> "Focus timer"
        DashboardPanelId.TimeTracker -> "Time tracker"
        DashboardPanelId.Clipboard -> "Clipboard"
        DashboardPanelId.QuickActions -> "Quick actions"
        DashboardPanelId.Media -> "Media & volume"
        DashboardPanelId.SystemTools -> "Windows & system"
        DashboardPanelId.NavigationShortcuts -> "Navigation"
        DashboardPanelId.QuickLaunch -> "Quick launch"
    }
    open fun layoutToolsWidthLabel(width: ToolsColumnWidth) = when (width) {
        ToolsColumnWidth.Narrow -> "Narrow"
        ToolsColumnWidth.Medium -> "Medium"
        ToolsColumnWidth.Wide -> "Wide"
    }
    open val moveUp = "Up"
    open val moveDown = "Down"
    open val cornerRadius = "Corner radius"
    open val layoutPhoneTabs = "Phone tabs"
    open val layoutPhoneTabsSub = "Bottom navigation order on phone"
    open val layoutPresets = "Layout presets"
    open val layoutPresetsSub = "Fast starting points for different scenarios"
    open val layoutPresetStream = "Stream"
    open val layoutPresetWork = "Work"
    open val layoutPresetGaming = "Gaming"
    open val layoutPresetMinimal = "Minimal"
    open val showAll = "Show all"
    open val hideAll = "Hide all"
    open val moveTop = "Top"
    open val moveBottom = "Bottom"
    open val customizeLayout = "Customize layout"
    open fun themeLabel(mode: ThemeMode) = when (mode) {
        ThemeMode.Dark -> "Dark"
        ThemeMode.Midnight -> "Midnight"
        ThemeMode.OLED -> "OLED"
        ThemeMode.Ocean -> "Ocean"
        ThemeMode.Sunset -> "Sunset"
        ThemeMode.Forest -> "Forest"
        ThemeMode.Neon -> "Neon"
        ThemeMode.Light -> "Light"
        ThemeMode.System -> "System"
    }
}

private class RussianAppStrings : AppStrings() {
    override val controlDeck get() = "Панель управления"
    override val connect get() = "Подключить"
    override val disconnect get() = "Отключить"
    override val connecting get() = "Подключение..."
    override val offline get() = "Офлайн"
    override val online get() = "Онлайн · ПК подключён"
    override val connectionError get() = "Ошибка подключения"
    override val newLayer get() = "Новый слой"
    override val delete get() = "Удалить"
    override val newMacro get() = "Новая кнопка"
    override val grid get() = "Сетка"
    override val ready get() = "Готово"
    override val edit get() = "Изменить"
    override val back get() = "Назад"
    override val save get() = "Сохранить"
    override val saved get() = "Сохранено"
    override val name get() = "Название"
    override val tabDeck get() = "Дек"
    override val tabTools get() = "Панели"
    override val tabMenu get() = "Меню"
    override val deckTitle get() = "Дек"
    override val quickActions get() = "Быстрые действия"
    override val quickActionsSub get() = "Горячие команды одним касанием"
    override val systemAudio get() = "Звук системы"
    override val systemAudioSub get() = "Громкость ПК в реальном времени"
    override val media get() = "Медиа"
    override val playing get() = "Играет"
    override val paused get() = "Пауза"
    override val micMute get() = "Микрофон"
    override val micOff get() = "Микрофон выкл."
    override val speakers get() = "Колонки"
    override val headphones get() = "Наушники"
    override val quickLaunch get() = "Быстрый запуск"
    override val quickLaunchSub get() = "Открывайте программы на ПК"
    override val navigation get() = "Навигация"
    override val navigationSub get() = "Папки и группы ссылок"
    override val windowsSystem get() = "Windows и система"
    override val windowsSystemSub get() = "Удерживайте Сон для подтверждения"
    override val moveToMonitor get() = "На монитор"
    override val moveToMonitorSub get() = "Перемещает активное окно на выбранный монитор"
    override fun monitor(n: Int) = "Монитор $n"
    override val minimizeAll get() = "Свернуть всё"
    override val maximize get() = "Развернуть"
    override val snapLeft get() = "Влево"
    override val snapRight get() = "Вправо"
    override val minimizeWin get() = "Свернуть окно"
    override val screenshot get() = "Скриншот"
    override val taskManager get() = "Диспетчер"
    override val killProcess get() = "Завершить процесс"
    override val sleep get() = "Сон"
    override val pcServer get() = "Сервер ПК"
    override val appearance get() = "Оформление"
    override val settings get() = "Настройки"
    override val settingsOverviewSub get() = "Короткая сводка перед разделами"
    override val settingsOverviewHint get() = "Открывайте только нужный раздел. Большинство изменений сохраняется автоматически."
    override fun layerGridTitle(name: String) = "Сетка слоя — $name"
    override val layerGridHint get() = "Размер сетки для этого слоя (2–8)."
    override val columns get() = "Столбцы"
    override val rows get() = "Строки"
    override val apply get() = "Применить"
    override val cancel get() = "Отмена"
    override val macroActionsBody get() = "Изменить кнопку или удалить её."
    override val sleepConfirmTitle get() = "Усыпить ПК?"
    override val sleepConfirmBody get() = "Компьютер перейдёт в режим сна."
    override val sleepNow get() = "Усыпить"
    override fun controlsCount(cols: Int, rows: Int, count: Int) = "$cols×$rows · кнопок: $count"
    override val language get() = "Язык"
    override val languageSub get() = "Язык интерфейса"
    override val english get() = "English"
    override val russian get() = "Русский"
    override val focusTracking get() = "Авто-слой"
    override val focusTrackingSub get() = "Меняет слой при смене активного окна на ПК"
    override val focusTrackingToggle get() = "Менять слой по активному окну"
    override val focusTrackingHint get() = "Правила можно добавить через JSON экспорта: processPattern -> pageId."
    override val hwMonitor get() = "Железо"
    override val hwMonitorSub get() = "CPU, RAM и сеть с ПК в реальном времени"
    override val clipboard get() = "Буфер обмена"
    override val clipboardSub get() = "Текст между ПК и телефоном"
    override val pasteFromPc get() = "Вставить с ПК"
    override fun foregroundApp(app: String) = "Активно: $app"
    override val cpu get() = "ЦП"
    override val ram get() = "ОЗУ"
    override val disk get() = "Диск"
    override val storage get() = "Диски"
    override val storageFree get() = "свободно"
    override fun networkDown(v: String) = "↓ $v Мбит/с"
    override fun networkUp(v: String) = "↑ $v Мбит/с"
    override val obsStream get() = "Стрим"
    override val obsRecord get() = "Запись"
    override val obsScenes get() = "Сцены"
    override val obsSources get() = "Источники"
    override val obsReplay get() = "Повтор"
    override val obsVirtualCam get() = "Вирт. камера"
    override val obsStudioMode get() = "Студия"
    override val obsRefresh get() = "Обновить"
    override val obsConnect get() = "Подключить"
    override val obsUrl get() = "WebSocket URL"
    override val obsPassword get() = "Пароль"
    override val lock get() = "Блокировка"
    override val paste get() = "Вставить"
    override val desktop get() = "Раб. стол"
    override val sync get() = "Синхр."
    override val copy get() = "Копировать"
    override val closeWin get() = "Закрыть"
    override val refresh get() = "Обновить"
    override val undo get() = "Отмена"
    override val cut get() = "Вырезать"
    override val redo get() = "Повтор"
    override val search get() = "Поиск"
    override val newTab get() = "Новая вкладка"
    override val previousTrack get() = "Пред. трек"
    override val nextTrack get() = "След. трек"
    override val discordSub get() = "Открывает Discord и отправляет полезные хоткеи"
    override val discordOpen get() = "Открыть"
    override val discordMute get() = "Мьют"
    override val discordDeafen get() = "Заглушить"
    override val discordPtt get() = "Рация"
    override val pomodoroTitle get() = "Фокус-таймер"
    override val pomodoroFocus get() = "Режим фокуса"
    override val pomodoroIdle get() = "Фокус-сессия"
    override val pomodoroStart get() = "Старт"
    override val pomodoroStop get() = "Стоп"
    override val pomodoroMinutes get() = "Длительность фокуса"
    override val timeTrackerTitle get() = "Трекер времени"
    override val timeTrackerIdle get() = "Нажмите проект для старта"
    override val timeTrackerStopLog get() = "Стоп и записать"
    override val processTitle get() = "Тяжёлые процессы"
    override val processSub get() = "Нажмите, чтобы завершить"
    override val cleanTemp get() = "Очистить Temp"
    override val devToolsTitle get() = "Dev и Git"
    override val devToolsSub get() = "Docker, Git, IDE"
    override val vscodeTest get() = "Тесты"
    override val vscodeFormat get() = "Формат"
    override val vscodeTerminal get() = "Терминал"
    override val wifiRestart get() = "Перезапуск Wi‑Fi"
    override val flushDns get() = "Сброс DNS"
    override val emptyRecycleBin get() = "Очистить корзину"
    override val streamToolsTitle get() = "Инструменты стрима"
    override val streamToolsSub get() = "OBS, кабинеты стрима, чат и клипы"
    override val streamToolsHint get() = "Twitch/YouTube открывают панели автора. Чат берёт ссылки из группы Stream Kit в настройках."
    override val streamChatTitle get() = "Чат стрима"
    override val streamChatSub get() = "Twitch и YouTube чат прямо на деке"
    override val streamChatHint get() = "Укажите Twitch-канал или ID YouTube-трансляции в настройках."
    override val twitchChannel get() = "Канал Twitch"
    override val youtubeVideoId get() = "ID YouTube live"
    override val embedChatInDashboard get() = "Показывать чат внутри дашборда"
    override val showTwitchChat get() = "Показывать Twitch чат"
    override val showYoutubeChat get() = "Показывать YouTube чат"
    override val openChat get() = "Чат"
    override val replayClip get() = "Повтор/клип"
    override val gameStatusTitle get() = "Игровой статус"
    override val gameStatusSub get() = "Авто-информация об игре с ПК"
    override val gameStatusHint get() = "Здоровье/карта/патроны CS2 требуют Game State Integration на ПК-сервере."
    override val gameOverlaySettings get() = "Игровой оверлей"
    override val gameOverlaySettingsSub get() = "Определение процессов, CS2-телеметрия и полезный игровой HUD"
    override val gameAutoProcesses get() = "Процессы для авто-показа"
    override val showHealth get() = "Здоровье"
    override val showAmmo get() = "Патроны"
    override val showMap get() = "Карта"
    override val showScore get() = "Счёт"
    override val gameNotDetected get() = "Поддерживаемая игра не обнаружена"
    override val health get() = "Здоровье"
    override val armor get() = "Броня"
    override val ammo get() = "Патроны"
    override val score get() = "Счёт"
    override val map get() = "Карта"
    override val phase get() = "Фаза"
    override val pcConfiguratorTitle get() = "Настройка с ПК"
    override val pcConfiguratorSub get() = "Откройте веб-редактор на компьютере"
    override val pcConfiguratorHint get() = "На ПК удобнее редактировать мышью и клавиатурой. Сервер уже отдаёт страницу настройки."
    override val openPcConfigurator get() = "Открыть настройщик"
    override val studyModeTitle get() = "Режим учёбы"
    override val studyModeSub get() = "Фокус-таймер, конспекты и набор вкладок"
    override val studyModeHint get() = "Фокус запускает таймер. Набор учёбы открывает календарь, документы и AI-помощник."
    override val startFocus get() = "Фокус"
    override val studyPack get() = "Набор учёбы"
    override val notes get() = "Конспекты"
    override val meetingModeTitle get() = "Режим встречи"
    override val meetingModeSub get() = "Микрофон и приложения для созвонов"
    override val meetingModeHint get() = "Микрофон переключает системный mute. Остальные кнопки открывают Discord/Teams/Zoom на ПК."
    override val pickFromGallery get() = "Выбрать из галереи"
    override val backgroundUrl get() = "Фон (URL картинки)"
    override val themes get() = "Тема"
    override val themesSub get() = "Цветовая палитра приложения"
    override val glassPanels get() = "Стеклянные панели"
    override val keepScreenOn get() = "Не гасить экран"
    override val accentColor get() = "Акцент (#hex)"
    override val pcConnection get() = "Подключение к ПК"
    override val pcConnectionSub get() = "WebSocket-адрес Windows-сервера"
    override val serverHost get() = "IP / хост сервера"
    override val port get() = "Порт"
    override val pinCode get() = "PIN-код"
    override val pinHint get() = "Защита сервера. Оставьте пустым, если PIN не задан на ПК."
    override val autoConnect get() = "Автоподключение при запуске"
    override val gridLayout get() = "Сетка дека"
    override val gridLayoutSub get() = "Размер сетки кнопок по умолчанию"
    override val showOnPanel get() = "Показать на панели"
    override val pathOrCommand get() = "Путь или команда"
    override val addProgram get() = "Добавить программу"
    override val restoreDefaults get() = "Сбросить"
    override val timeTrackerSettings get() = "Трекер времени"
    override val timeTrackerSettingsSub get() = "Проекты на дашборде · экспорт CSV"
    override val timeTrackerStorageHint get() = "Записи хранятся локально в памяти приложения. Нажмите «Экспорт CSV», чтобы получить таблицу для копирования."
    override val addProject get() = "Добавить проект"
    override val exportCsv get() = "Экспорт CSV"
    override fun entriesLogged(n: Int) = "Записей: $n"
    override val navigationFolders get() = "Папки навигации"
    override val navigationFoldersSub get() = "Ярлыки проводника"
    override val urlGroups get() = "Группы URL"
    override val urlGroupsSub get() = "Несколько ссылок — через |"
    override val streamChatSettings get() = "Чат стрима"
    override val streamChatSettingsSub get() = "Twitch/YouTube чат для дашборда"
    override val importExport get() = "Импорт / Экспорт"
    override val importExportSub get() = "Резервная копия дека в JSON"
    override val exportDeck get() = "Экспорт дека"
    override val importDeck get() = "Импорт дека"
    override val pasteJsonImport get() = "Вставьте JSON для импорта"
    override val exportedJson get() = "Экспортированный JSON"
    override val editorTitle get() = "Редактор кнопки"
    override val livePreview get() = "Превью"
    override val visual get() = "Внешний вид"
    override val subtitle get() = "Подзаголовок"
    override val icon get() = "Иконка"
    override val imageUrl get() = "URL картинки"
    override val gradient get() = "Градиент"
    override val activeIcon get() = "Иконка активного состояния"
    override val activeColor get() = "Цвет активного состояния"
    override val iconPresets get() = "Пресеты иконок"
    override val toggleMode get() = "Режим переключателя"
    override val twoStateButton get() = "Кнопка с двумя состояниями"
    override fun macroSteps(n: Int) = "Шаги макроса ($n)"
    override fun step(n: Int) = "Шаг $n"
    override val actionType get() = "Тип действия"
    override val payloadKey get() = "Ключ payload"
    override val payloadValue get() = "Значение payload"
    override val addStep get() = "Добавить шаг"
    override val macroTemplates get() = "Шаблоны"
    override val simpleActions get() = "Простые действия"
    override val advancedPrograms get() = "Программируемые макросы"
    override val programMacroHint get() = "Программируемые макросы умеют последовательности, задержки, переменные, циклы и условия."
    override fun macroTemplateLabel(key: String) = when (key) {
        "browser" -> "Открыть браузер"
        "website" -> "Открыть сайт"
        "app" -> "Открыть приложение"
        "obs_stream" -> "OBS стрим"
        "obs_replay" -> "Сохранить повтор"
        "screenshot" -> "Скриншот"
        "discord_mute" -> "Discord mute"
        "mic_mute" -> "Микрофон mute"
        "focus_mode" -> "Режим фокуса"
        "meeting_mute" -> "Mute встречи"
        "study_pack" -> "Набор учёбы"
        "twitch_chat" -> "Twitch чат"
        "youtube_studio" -> "YouTube Live"
        "pc_configurator" -> "Настройка ПК"
        "cs2_gsi_help" -> "CS2 HUD"
        "window_layout" -> "Раскладка окон"
        "move_monitor_2" -> "На монитор 2"
        "game_mode" -> "Игровой режим"
        "stream_start_pack" -> "Старт стрима"
        "work_focus_pack" -> "Рабочий фокус"
        "program_sequence" -> "Последовательность"
        "program_loop" -> "Цикл"
        "program_timer" -> "Таймер"
        "program_condition" -> "Условие"
        else -> key
    }
    override val colorPresets get() = "Пресеты цветов"
    override val rowSpan get() = "Строк"
    override val columnSpan get() = "Столбцов"
    override val navigatePageHint get() = "Выберите слой или вставьте ID:"
    override val launchAdminHint get() = "Для UAC добавьте шаг: LaunchProcess, ключ runAsAdmin, значение true"
    override val whenToggle get() = "Когда (toggle)"
    override val delayMs get() = "Задержка мс"
    override val targetLayerId get() = "ID целевого слоя"
    override val folderPath get() = "Путь к папке"
    override val urls get() = "Ссылки"
    override val groupName get() = "Название группы"
    override val project get() = "Проект"
    override val layoutCustomization get() = "Раскладка"
    override val layoutCustomizationSub get() = "Меняйте зоны и панели, скрывайте ненужные блоки"
    override val layoutZones get() = "Зоны экрана (планшет)"
    override val layoutZonesSub get() = "Порядок: боковая панель, дек, колонка панелей"
    override val layoutPanels get() = "Панели"
    override val layoutPanelsSub get() = "Порядок и видимость панелей инструментов"
    override val layoutSidebarVisible get() = "Боковая панель на планшете"
    override val layoutToolsWidth get() = "Ширина колонки панелей"
    override fun layoutZoneLabel(zone: DashboardZone) = when (zone) {
        DashboardZone.Sidebar -> "Боковая (слои и подключение)"
        DashboardZone.Deck -> "Дек (сетка макросов)"
        DashboardZone.ToolsColumn -> "Панели (инструменты)"
    }
    override fun layoutPanelLabel(id: DashboardPanelId) = when (id) {
        DashboardPanelId.HardwareMonitor -> "Мониторинг железа"
        DashboardPanelId.ProcessMonitor -> "Процессы"
        DashboardPanelId.DevTools -> "Dev / Git / Docker"
        DashboardPanelId.StreamTools -> "Инструменты стрима"
        DashboardPanelId.StreamChat -> "Чат стрима"
        DashboardPanelId.GameStatus -> "Игровой статус"
        DashboardPanelId.PcConfigurator -> "Настройка с ПК"
        DashboardPanelId.Discord -> "Discord"
        DashboardPanelId.StudyMode -> "Учёба"
        DashboardPanelId.MeetingMode -> "Встречи"
        DashboardPanelId.Pomodoro -> "Фокус-таймер"
        DashboardPanelId.TimeTracker -> "Трекер времени"
        DashboardPanelId.Clipboard -> "Буфер обмена"
        DashboardPanelId.QuickActions -> "Быстрые действия"
        DashboardPanelId.Media -> "Медиа и громкость"
        DashboardPanelId.SystemTools -> "Windows и система"
        DashboardPanelId.NavigationShortcuts -> "Навигация"
        DashboardPanelId.QuickLaunch -> "Быстрый запуск"
    }
    override fun layoutToolsWidthLabel(width: ToolsColumnWidth) = when (width) {
        ToolsColumnWidth.Narrow -> "Узкая"
        ToolsColumnWidth.Medium -> "Средняя"
        ToolsColumnWidth.Wide -> "Широкая"
    }
    override val moveUp get() = "Вверх"
    override val moveDown get() = "Вниз"
    override val cornerRadius get() = "Скругление углов"
    override val layoutPhoneTabs get() = "Вкладки телефона"
    override val layoutPhoneTabsSub get() = "Порядок нижней навигации на телефоне"
    override val layoutPresets get() = "Пресеты раскладки"
    override val layoutPresetsSub get() = "Быстрые варианты под разные сценарии"
    override val layoutPresetStream get() = "Стрим"
    override val layoutPresetWork get() = "Работа"
    override val layoutPresetGaming get() = "Игра"
    override val layoutPresetMinimal get() = "Минимум"
    override val showAll get() = "Показать всё"
    override val hideAll get() = "Скрыть всё"
    override val moveTop get() = "В начало"
    override val moveBottom get() = "В конец"
    override val customizeLayout get() = "Настроить раскладку"
    override fun themeLabel(mode: ThemeMode) = when (mode) {
        ThemeMode.Dark -> "Тёмная"
        ThemeMode.Midnight -> "Полночь"
        ThemeMode.OLED -> "OLED"
        ThemeMode.Ocean -> "Океан"
        ThemeMode.Sunset -> "Закат"
        ThemeMode.Forest -> "Лес"
        ThemeMode.Neon -> "Неон"
        ThemeMode.Light -> "Светлая"
        ThemeMode.System -> "Системная"
    }
}

private val englishStrings = AppStrings()

private val russianStrings = RussianAppStrings()

val LocalAppStrings = staticCompositionLocalOf { englishStrings }

@Composable
fun strings(): AppStrings = LocalAppStrings.current

fun stringsFor(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.English -> englishStrings
    AppLanguage.Russian -> russianStrings
}
